### ISSUE TITLE
No module named 'celltics.lib'

### ISSUE THREAD

**Issue by azerxu** [MGHComputationalPathology/CellTics#2]
Traceback (most recent call last):
  File "vargroup.py", line 23, in <module>
    from celltics.lib import chunks, get_indel_from_cigar
ModuleNotFoundError: No module named 'celltics.lib'

No lib module found in celltics

**Comment by alliemacleay** [comment]
Did you do this first?

`python setup.py`

**Comment by alliemacleay** [comment]
The lib file mistakingly was not checked in.  This is fixed now and merged to master!
